let name = "Elakkiya.G"; 
let age = 19;           
let likesCoding = false;
let favoriteLanguages = ["Html","Css","java script"];
let num1 = 20;
let num2 = 8;
let sum = num1 + num2;
let difference = num1 - num2;
let product = num1 * num2;
let quotient = num1 / num2;
let remainder = num1 % num2;
console.log("Name:",name);
console.log("Age:", age);
console.log("Likes Coding:", likesCoding);
console.log("Favorite Programming Languages:", favoriteLanguages);
console.log("Sum:", sum);
console.log("Difference:", difference);
console.log("Product:", product);
console.log("Quotient:", quotient);
console.log("Remainder:", remainder);